#!/bin/python3

import math
import os
import random
import re
import sys
if __name__ == '__main__':
    
    number = int(input())
result = 0
maximum = 0
while number > 0:
    if number % 2 == 1:
        result += 1
        if result > maximum:
            maximum = result
    else:
        result = 0
    number //= 2
print(maximum)
